config/routes.rb
Rails.application.routes.draw do
 
   devise_for :users
   resources :gabriels
   get 'home/about'
   
   root 'gabriels#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @answer = 2 + 2

  end
  
  def About
    
    @answer = 2 + 2

  end
  
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to 'Gabriels App', root_path, class:"navbar-brand" %>
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <% if user_signed_in? %>
          <li class="nav-item">
        <%= link_to "Add Gabriels", new_gabriel_path, class: "nav-link" %>
        </li>
        
         <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
         <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        </li>
        <% else %>
          <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
         <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
        <% end %>
        <li class="nav-item">
        <%= link_to "About Us", home_about_path, class: "nav-link" %>
        </li>
      
       
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

<p>

   2 + 2 =  <%= @answer %>

</p>

app/views/home/index.html.erb
<h1>Main Page</h1>
Gabriels<br/>
Gabriels<br/>
Gabriels<br/>
And more Gabriels<br/>