config/routes.rb
Rails.application.routes.draw do
 
   devise_for :users
   resources :gabriels
   get 'home/about'
   
   root 'gabriels#index'
end

app/models/gabriel.rb
class Gabriel < ApplicationRecord
    belongs_to :user
end

app/controllers/gabriels_controller.rb
class GabrielsController < ApplicationController
  before_action :set_gabriel, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [ :edit, :update, :destroy]

  # GET /gabriels or /gabriels.json
  def index
    @gabriels = Gabriel.all
  end

  # GET /gabriels/1 or /gabriels/1.json
  def show
  end

  # GET /gabriels/new
  def new
    @gabriel = current_user.gabriels.build

  end

  # GET /gabriels/1/edit
  def edit
  end

  # POST /gabriels or /gabriels.json
  def create
   #@gabriel = Gabriel.new(gabriel_params)
    @gabriel = current_user.gabriels.build (gabriel_params)
    respond_to do |format|
      if @gabriel.save
        format.html { redirect_to @gabriel, notice: "Gabriel was successfully created." }
        format.json { render :show, status: :created, location: @gabriel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gabriel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gabriels/1 or /gabriels/1.json
  def update
    respond_to do |format|
      if @gabriel.update(gabriel_params)
        format.html { redirect_to @gabriel, notice: "Gabriel was successfully updated." }
        format.json { render :show, status: :ok, location: @gabriel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gabriel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gabriels/1 or /gabriels/1.json
  def destroy
    @gabriel.destroy
    respond_to do |format|
      format.html { redirect_to gabriels_url, notice: "Gabriel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

   def correct_user
    @gabriel = current_user.gabriels.find_by(id: params[:id])
    redirect_to gabriels_path, notice: "Not authorized to do this action..." if @gabriel.nil?
   end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gabriel
      @gabriel = Gabriel.find(params[:id])
    end

    def gabriel_params
      params.require(:gabriel).permit(:first_name, :last_name, :emails, :phone, :twitter, :user_id)
    end
end

app/views/gabriels/_form.html.erb
<%= form_with(model: gabriel) do |form| %>
  <% if gabriel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gabriel.errors.count, "error") %> prohibited this gabriel from being saved:</h2>

      <ul>
        <% gabriel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :emails %>
    <%= form.text_field :emails, class: "form-control", placeholder: "example@email.com" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control", placeholder: " (XX) 00000-0000 "%>
  </div>

  <div class="field form-group">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, class: "form-control", placeholder: "@example" %>
  </div>
   
   <div class="field form-group">
    <%= form.number_field :user_id, id: :gabriels_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>


<br/>

  <div class="actions">
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/gabriels/edit.html.erb
<h1>Editing Gabriel</h1>
<br/>
<%= render 'form', gabriel: @gabriel %> 
<br/>
<%= link_to 'Delete', @gabriel, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
<br/>
<br/>
<%= link_to 'Show', @gabriel, class: "btn btn-dark" %> 
<%= link_to 'Back', gabriels_path, class: "btn btn-dark" %>

app/views/gabriels/index.html.erb
<% if user_signed_in? %>


<h1>Gabriels List</h1>

<table class="table table-hover table-dark table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Emails</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th> </th>
    </tr>
  </thead>

  <tbody>
    <% @gabriels.each do |gabriel| %>
    <% if gabriel.user == current_user%>
      <tr>
        <td><%= link_to gabriel.first_name + " " + gabriel.last_name , gabriel%></td>
        <td><%= gabriel.emails %></td>
        <td><%= gabriel.phone %></td>
        <td><%= gabriel.twitter %></td>
        <td><%= link_to 'Delete', gabriel_path(gabriel), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gabriel', new_gabriel_path, class: "btn btn-dark" %>

<% else %>

<h1>Main Page</h1>
Gabriels<br/>
Gabriels<br/>
Gabriels<br/>
And more Gabriels<br/>

<% end %>

app/views/gabriels/new.html.erb
<h1>Add New Gabriel</h1>
<br/>
<%= render 'form', gabriel: @gabriel %>
<br/>
<%= link_to 'Back', gabriels_path, class: "btn btn-dark"%>

app/views/gabriels/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"> <%= @gabriel.first_name %> <%= @gabriel.last_name %></h1>
  <p class="lead"> <%= @gabriel.emails %> <br/> ------------------------ <br/> <%= @gabriel.phone %></p>
  <hr class="my-4">
  <p> <%= @gabriel.twitter %> </p>
  <p class="lead">
   <%= link_to 'Edit', edit_gabriel_path(@gabriel), class: "btn btn-dark" %> 
<%= link_to 'Back', gabriels_path, class: "btn btn-dark" %>
  </p>
</div>